# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170810_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.CharField(default=uuid.UUID('67f577b1-5165-4015-953d-d2f256f77c32'), max_length=40)),
            ],
        ),
    ]
