# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20170828_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='SharedWith', to=settings.AUTH_USER_MODEL),
        ),
    ]
